# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

csc_tocsr <- function(n_row, n_col, Ap, Ai, Ax) {
    .Call('_Azimuth_csc_tocsr', PACKAGE = 'Azimuth', n_row, n_col, Ap, Ai, Ax)
}

