# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ScoreHelper <- function(snn, query_pca, query_dists, corrected_nns, k_snn, subtract_first_nn, display_progress) {
    .Call('_SeuratMapper_ScoreHelper', PACKAGE = 'SeuratMapper', snn, query_pca, query_dists, corrected_nns, k_snn, subtract_first_nn, display_progress)
}

